// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartFarm.Infrastructure.Persistence;

#nullable disable

namespace SmartFarm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartFarmDbContext))]
    [Migration("20260924144711_CropGrowthPlantingSeason")]
    partial class CropGrowthPlantingSeason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartFarm.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("app_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_users_role_scope", "(role IN ('PlatformAdmin', 'PlatformTechnician') AND tenant_id IS NULL AND farm_id IS NULL) OR (role = 'FarmOwner' AND farm_id IS NULL) OR (role = 'Farmer' AND ((tenant_id IS NULL AND farm_id IS NULL) OR (tenant_id IS NOT NULL AND farm_id IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("crops", null, t =>
                        {
                            t.HasCheckConstraint("ck_crops_scope", "(is_system_defined = true AND tenant_id IS NULL) OR (is_system_defined = false AND tenant_id IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System tomato crop",
                            IsSystemDefined = true,
                            Name = "Tomato",
                            NormalizedName = "TOMATO",
                            ScientificName = "Solanum lycopersicum"
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.CropVariety", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CropId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("CropId", "TenantId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("crop_varieties", null, t =>
                        {
                            t.HasCheckConstraint("ck_crop_varieties_scope", "(is_system_defined = true AND tenant_id IS NULL) OR (is_system_defined = false AND tenant_id IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "System tomato variety",
                            IsSystemDefined = true,
                            Name = "Beef F1",
                            NormalizedName = "BEEF F1"
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.EnvironmentalRequirement", b =>
                {
                    b.Property<Guid>("GrowthStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("growth_stage_id");

                    b.Property<string>("ParameterCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("parameter_code");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("max_value");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("min_value");

                    b.Property<decimal>("TargetValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("target_value");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.HasKey("GrowthStageId", "ParameterCode");

                    b.ToTable("environmental_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_environmental_requirement_range", "min_value <= target_value AND target_value <= max_value");
                        });

                    b.HasData(
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ParameterCode = "Temperature",
                            MaxValue = 28m,
                            MinValue = 20m,
                            TargetValue = 24m,
                            Unit = "C"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ParameterCode = "SoilMoisture",
                            MaxValue = 80m,
                            MinValue = 65m,
                            TargetValue = 72m,
                            Unit = "%"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ParameterCode = "AirHumidity",
                            MaxValue = 75m,
                            MinValue = 60m,
                            TargetValue = 70m,
                            Unit = "%"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ParameterCode = "Ph",
                            MaxValue = 6.5m,
                            MinValue = 5.5m,
                            TargetValue = 6m,
                            Unit = "pH"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ParameterCode = "Temperature",
                            MaxValue = 30m,
                            MinValue = 21m,
                            TargetValue = 25m,
                            Unit = "C"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ParameterCode = "SoilMoisture",
                            MaxValue = 78m,
                            MinValue = 60m,
                            TargetValue = 70m,
                            Unit = "%"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ParameterCode = "AirHumidity",
                            MaxValue = 75m,
                            MinValue = 55m,
                            TargetValue = 65m,
                            Unit = "%"
                        },
                        new
                        {
                            GrowthStageId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ParameterCode = "Ph",
                            MaxValue = 6.8m,
                            MinValue = 5.5m,
                            TargetValue = 6.2m,
                            Unit = "pH"
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_text");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<decimal>("TotalAreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_area_m2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("farms", null, t =>
                        {
                            t.HasCheckConstraint("ck_farms_latitude", "latitude IS NULL OR latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_farms_longitude", "longitude IS NULL OR longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_farms_max_area", "total_area_m2 <= 1000000");

                            t.HasCheckConstraint("ck_farms_total_area", "total_area_m2 > 0");
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area_m2");

                    b.Property<decimal>("AvailableAreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available_area_m2");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("boundary_geo_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soil_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Name")
                        .IsUnique();

                    b.ToTable("fields", null, t =>
                        {
                            t.HasCheckConstraint("ck_fields_area", "area_m2 > 0");

                            t.HasCheckConstraint("ck_fields_available_area", "available_area_m2 >= 0 AND available_area_m2 <= area_m2");

                            t.HasCheckConstraint("ck_fields_boundary_json", "boundary_geo_json IS NULL OR jsonb_typeof(boundary_geo_json) = 'object'");

                            t.HasCheckConstraint("ck_fields_latitude", "latitude IS NULL OR latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_fields_longitude", "longitude IS NULL OR longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.GrowthProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid?>("SourceProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_profile_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VarietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("variety_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceProfileId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VarietyId");

                    b.HasIndex("CropId", "VarietyId", "TenantId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("growth_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_growth_profiles_scope", "(is_system_defined = true AND tenant_id IS NULL) OR (is_system_defined = false AND tenant_id IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CropId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "System default profile",
                            IsDefault = true,
                            IsSystemDefined = true,
                            Name = "Default Tomato Beef Profile",
                            NormalizedName = "DEFAULT TOMATO BEEF PROFILE",
                            VarietyId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.GrowthStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<Guid>("GrowthProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("growth_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stage_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("GrowthProfileId", "Name")
                        .IsUnique();

                    b.HasIndex("GrowthProfileId", "StageOrder")
                        .IsUnique();

                    b.ToTable("growth_stages", null, t =>
                        {
                            t.HasCheckConstraint("ck_growth_stages_duration", "duration_days > 0");

                            t.HasCheckConstraint("ck_growth_stages_order", "stage_order > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 20,
                            GrowthProfileId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Seedling",
                            StageOrder = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            GrowthProfileId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Vegetative",
                            StageOrder = 2
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.PlantingSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_end_date");

                    b.Property<decimal?>("ActualYieldKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_yield_kg");

                    b.Property<string>("CloseNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("close_notes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<Guid>("CurrentGrowthStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_growth_stage_id");

                    b.Property<DateOnly>("ExpectedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_end_date");

                    b.Property<Guid>("GrowthProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("growth_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VarietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("variety_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("CurrentGrowthStageId");

                    b.HasIndex("GrowthProfileId");

                    b.HasIndex("VarietyId");

                    b.HasIndex("ZoneId")
                        .IsUnique()
                        .HasFilter("status = 'InProgress'");

                    b.ToTable("planting_seasons", null, t =>
                        {
                            t.HasCheckConstraint("ck_planting_seasons_dates", "expected_end_date >= start_date + 20");

                            t.HasCheckConstraint("ck_planting_seasons_yield", "actual_yield_kg IS NULL OR actual_yield_kg >= 0");
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at_utc");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("access_token_jti");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenJti")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AppUserId", "RevokedAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.SeasonAppliedRequirement", b =>
                {
                    b.Property<Guid>("PlantingSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("planting_season_id");

                    b.Property<string>("ParameterCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("parameter_code");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("max_value");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("min_value");

                    b.Property<decimal>("TargetValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("target_value");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.HasKey("PlantingSeasonId", "ParameterCode");

                    b.ToTable("season_applied_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_season_applied_requirement_range", "min_value <= target_value AND target_value <= max_value");
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.SeasonStageTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CurrentGrowthStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_growth_stage_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PlantingSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("planting_season_id");

                    b.Property<Guid>("PreviousGrowthStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_growth_stage_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CurrentGrowthStageId");

                    b.HasIndex("PlantingSeasonId");

                    b.HasIndex("PreviousGrowthStageId");

                    b.ToTable("season_stage_transitions", (string)null);
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subdomain");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasFilter("tax_code IS NOT NULL");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.UserZoneAccess", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<bool>("CanControl")
                        .HasColumnType("boolean")
                        .HasColumnName("can_control");

                    b.HasKey("AppUserId", "ZoneId");

                    b.HasIndex("ZoneId");

                    b.ToTable("user_zone_accesses", (string)null);
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area_m2");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("boundary_geo_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_type");

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "Name")
                        .IsUnique();

                    b.ToTable("zones", null, t =>
                        {
                            t.HasCheckConstraint("ck_zones_area", "area_m2 > 0");

                            t.HasCheckConstraint("ck_zones_boundary_json", "boundary_geo_json IS NULL OR jsonb_typeof(boundary_geo_json) = 'object'");
                        });
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Farm", "Farm")
                        .WithMany("Farmers")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Farm");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Crop", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.CropVariety", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.Crop", "Crop")
                        .WithMany("Varieties")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Crop");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.EnvironmentalRequirement", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.GrowthStage", "GrowthStage")
                        .WithMany("Requirements")
                        .HasForeignKey("GrowthStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowthStage");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Farm", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Farms")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Field", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.GrowthProfile", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.Crop", "Crop")
                        .WithMany("GrowthProfiles")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.GrowthProfile", "SourceProfile")
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.CropVariety", "Variety")
                        .WithMany("GrowthProfiles")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Crop");

                    b.Navigation("SourceProfile");

                    b.Navigation("Tenant");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.GrowthStage", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.GrowthProfile", "GrowthProfile")
                        .WithMany("Stages")
                        .HasForeignKey("GrowthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowthProfile");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.PlantingSeason", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.GrowthStage", "CurrentGrowthStage")
                        .WithMany()
                        .HasForeignKey("CurrentGrowthStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.GrowthProfile", "GrowthProfile")
                        .WithMany()
                        .HasForeignKey("GrowthProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.CropVariety", "Variety")
                        .WithMany()
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFarm.Domain.Entities.Zone", "Zone")
                        .WithMany("PlantingSeasons")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("CurrentGrowthStage");

                    b.Navigation("GrowthProfile");

                    b.Navigation("Variety");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.SeasonAppliedRequirement", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.PlantingSeason", "PlantingSeason")
                        .WithMany("AppliedRequirements")
                        .HasForeignKey("PlantingSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingSeason");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.SeasonStageTransition", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.GrowthStage", "CurrentGrowthStage")
                        .WithMany()
                        .HasForeignKey("CurrentGrowthStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.PlantingSeason", "PlantingSeason")
                        .WithMany("StageTransitions")
                        .HasForeignKey("PlantingSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.GrowthStage", "PreviousGrowthStage")
                        .WithMany()
                        .HasForeignKey("PreviousGrowthStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("CurrentGrowthStage");

                    b.Navigation("PlantingSeason");

                    b.Navigation("PreviousGrowthStage");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.UserZoneAccess", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.AppUser", "AppUser")
                        .WithMany("ZoneAccesses")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartFarm.Domain.Entities.Zone", "Zone")
                        .WithMany("UserAccesses")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Zone", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Field", "Field")
                        .WithMany("Zones")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ZoneAccesses");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Crop", b =>
                {
                    b.Navigation("GrowthProfiles");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.CropVariety", b =>
                {
                    b.Navigation("GrowthProfiles");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Farmers");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Field", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.GrowthProfile", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.GrowthStage", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.PlantingSeason", b =>
                {
                    b.Navigation("AppliedRequirements");

                    b.Navigation("StageTransitions");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Zone", b =>
                {
                    b.Navigation("PlantingSeasons");

                    b.Navigation("UserAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
