using Microsoft.EntityFrameworkCore;
using SmartFarm.Application.Common.Exceptions;
using SmartFarm.Application.Features.Finance;
using SmartFarm.Domain.Entities;
using SmartFarm.Domain.Enums;
using SmartFarm.Infrastructure.Persistence;

namespace SmartFarm.Infrastructure.Finance;

public sealed class FinanceService(SmartFarmDbContext db, TimeProvider clock) : IFinanceService
{
    public async Task<IReadOnlyList<FinanceTransactionView>> ListAsync(Guid ownerId, Guid tenantId, Guid farmId, DateTime? from, DateTime? to, CancellationToken ct)
    { await OwnerFarm(ownerId, tenantId, farmId, ct); Range(from, to); var q = db.FinanceTransactions.AsNoTracking().Where(x => x.TenantId == tenantId && x.FarmId == farmId && x.ArchivedAtUtc == null); if (from.HasValue) q = q.Where(x => x.OccurredAtUtc >= from); if (to.HasValue) q = q.Where(x => x.OccurredAtUtc <= to); return (await q.OrderByDescending(x => x.OccurredAtUtc).ToListAsync(ct)).Select(View).ToList(); }
    public async Task<FinanceTransactionView> CreateAsync(Guid ownerId, Guid tenantId, Guid farmId, FinanceTransactionType type, CreateFinanceCommand c, CancellationToken ct)
    { await OwnerFarm(ownerId, tenantId, farmId, ct); Validate(c.Amount, c.OccurredAtUtc, c.Description, type, c.ExpenseCategory); var x = new FinanceTransaction { TenantId = tenantId, FarmId = farmId, TransactionType = type, ExpenseCategory = type == FinanceTransactionType.Expense ? c.ExpenseCategory : null, Amount = c.Amount, OccurredAtUtc = c.OccurredAtUtc, Description = Required(c.Description, "description", 500), Reference = Optional(c.Reference, 200), CreatedByOwnerId = ownerId }; db.FinanceTransactions.Add(x); await db.SaveChangesAsync(ct); return View(x); }
    public async Task<FinanceTransactionView> UpdateAsync(Guid ownerId, Guid tenantId, Guid farmId, Guid id, UpdateFinanceCommand c, CancellationToken ct)
    { await OwnerFarm(ownerId, tenantId, farmId, ct); var x = await Find(tenantId, farmId, id, ct); Validate(c.Amount, c.OccurredAtUtc, c.Description, x.TransactionType, c.ExpenseCategory); x.Amount = c.Amount; x.OccurredAtUtc = c.OccurredAtUtc; x.Description = Required(c.Description, "description", 500); x.Reference = Optional(c.Reference, 200); x.ExpenseCategory = x.TransactionType == FinanceTransactionType.Expense ? c.ExpenseCategory : null; await db.SaveChangesAsync(ct); return View(x); }
    public async Task ArchiveAsync(Guid ownerId, Guid tenantId, Guid farmId, Guid id, CancellationToken ct) { await OwnerFarm(ownerId, tenantId, farmId, ct); var x = await Find(tenantId, farmId, id, ct); x.ArchivedAtUtc = clock.GetUtcNow().UtcDateTime; await db.SaveChangesAsync(ct); }
    public async Task<CashFlowReportView> ReportAsync(Guid ownerId, Guid tenantId, Guid farmId, DateTime? from, DateTime? to, CancellationToken ct)
    { await OwnerFarm(ownerId, tenantId, farmId, ct); Range(from, to); var q = db.FinanceTransactions.AsNoTracking().Where(x => x.TenantId == tenantId && x.FarmId == farmId && x.ArchivedAtUtc == null); if (from.HasValue) q = q.Where(x => x.OccurredAtUtc >= from); if (to.HasValue) q = q.Where(x => x.OccurredAtUtc <= to); var rows = await q.ToListAsync(ct); var revenue = rows.Where(x => x.TransactionType == FinanceTransactionType.Revenue).Sum(x => x.Amount); var expense = rows.Where(x => x.TransactionType == FinanceTransactionType.Expense).Sum(x => x.Amount); var by = Enum.GetValues<ExpenseCategory>().ToDictionary(x => x, x => rows.Where(r => r.ExpenseCategory == x).Sum(r => r.Amount)); return new(farmId, from, to, revenue, expense, revenue - expense, by); }
    private async Task OwnerFarm(Guid id, Guid tenant, Guid farm, CancellationToken ct) { if (!await db.AppUsers.AnyAsync(x => x.Id == id && x.TenantId == tenant && x.Role == UserRole.FarmOwner && x.Status == AccountStatus.Active, ct)) throw new AuthorizationException(); if (!await db.Farms.AnyAsync(x => x.Id == farm && x.TenantId == tenant && x.ArchivedAtUtc == null, ct)) throw new ResourceNotFoundException("Farm was not found in the authenticated Tenant."); }
    private async Task<FinanceTransaction> Find(Guid tenant, Guid farm, Guid id, CancellationToken ct) => await db.FinanceTransactions.SingleOrDefaultAsync(x => x.Id == id && x.TenantId == tenant && x.FarmId == farm && x.ArchivedAtUtc == null, ct) ?? throw new ResourceNotFoundException("Finance transaction was not found in this Farm.");
    private static void Validate(decimal amount, DateTime occurred, string description, FinanceTransactionType type, ExpenseCategory? category) { if (amount <= 0) throw new RequestValidationException("amount", "Amount must be positive."); if (occurred.Kind != DateTimeKind.Utc) throw new RequestValidationException("occurredAtUtc", "Occurrence time must be UTC."); Required(description, "description", 500); if (type == FinanceTransactionType.Expense && category is null) throw new RequestValidationException("expenseCategory", "Expense category is required."); }
    private static void Range(DateTime? from, DateTime? to) { if (from.HasValue && from.Value.Kind != DateTimeKind.Utc || to.HasValue && to.Value.Kind != DateTimeKind.Utc || from > to) throw new RequestValidationException("range", "Use a valid UTC range where fromUtc is not after toUtc."); }
    private static FinanceTransactionView View(FinanceTransaction x) => new(x.Id, x.FarmId, x.TransactionType, x.ExpenseCategory, x.Amount, x.OccurredAtUtc, x.Description, x.Reference, x.CreatedAtUtc);
    internal static string Required(string? s, string field, int max) { s = s?.Trim(); if (string.IsNullOrWhiteSpace(s) || s.Length > max) throw new RequestValidationException(field, $"{field} is required and must not exceed {max} characters."); return s; }
    internal static string? Optional(string? s, int max) { s = s?.Trim(); if (string.IsNullOrEmpty(s)) return null; if (s.Length > max) throw new RequestValidationException("value", $"Value must not exceed {max} characters."); return s; }
}
