using Microsoft.EntityFrameworkCore;
using SmartFarm.Application.Common.Exceptions;
using SmartFarm.Application.Features.Finance;
using SmartFarm.Domain.Entities;
using SmartFarm.Domain.Enums;
using SmartFarm.Infrastructure.Persistence;

namespace SmartFarm.Infrastructure.Finance;

public sealed class ServiceRequestService(SmartFarmDbContext db, TimeProvider clock) : IServiceRequestService
{
    public async Task<ServiceRequestView> CreateAsync(Guid owner, Guid tenant, Guid farm, CreateServiceRequestCommand c, CancellationToken ct)
    {
        await OwnerFarm(owner, tenant, farm, ct); var d = await db.Devices.SingleOrDefaultAsync(x => x.Id == c.DeviceId && x.FarmId == farm && x.ZoneId == c.ZoneId && x.Status != DeviceStatus.Decommissioned, ct) ?? throw new ResourceNotFoundException("Device was not found in this Farm and Zone.");
        if (await db.ServiceRequests.AnyAsync(x => x.DeviceId == d.Id && x.Status != ServiceRequestStatus.Closed, ct)) throw new ResourceConflictException("Device already has an active Service Request.");
        var r = new ServiceRequest { TenantId = tenant, FarmId = farm, ZoneId = c.ZoneId, DeploymentRequestId = d.DeploymentRequestId, DeviceId = d.Id, CurrentDeviceId = d.Id, CreatedByOwnerId = owner, Source = "Owner", FailureCode = FinanceService.Required(c.FailureCode, "failureCode", 100), Description = FinanceService.Required(c.Description, "description", 2000) };
        db.ServiceRequests.Add(r); Add(r, owner, ServiceHistoryEventType.Created, ServiceRequestStatus.Open, ServiceRequestStatus.Open, r.Description); d.Status = DeviceStatus.MaintenanceRequired; await db.SaveChangesAsync(ct); return await Load(r.Id, ct);
    }
    public async Task<IReadOnlyList<ServiceRequestView>> ListAsync(Guid user, Guid? tenant, CancellationToken ct) { var u = await User(user, ct); var q = Query().AsNoTracking(); if (u.Role == UserRole.FarmOwner) { if (tenant is null) throw new AuthorizationException(); q = q.Where(x => x.TenantId == tenant); } else if (u.Role == UserRole.PlatformTechnician) q = q.Where(x => x.AssignedTechnicianId == user); else if (u.Role != UserRole.PlatformAdmin) throw new AuthorizationException(); return (await q.OrderByDescending(x => x.CreatedAtUtc).ToListAsync(ct)).Select(View).ToList(); }
    public async Task<ServiceRequestView> GetAsync(Guid user, Guid? tenant, Guid id, CancellationToken ct) { var u = await User(user, ct); var r = await Query().AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new ResourceNotFoundException("Service Request was not found."); Visible(u, tenant, r); return View(r); }
    public async Task<ServiceRequestView> AssignAsync(Guid admin, Guid id, AssignServiceRequestCommand c, CancellationToken ct)
    { await Role(admin, UserRole.PlatformAdmin, ct); var tech = await db.AppUsers.SingleOrDefaultAsync(x => x.Id == c.TechnicianUserId && x.Role == UserRole.PlatformTechnician && x.Status == AccountStatus.Active && x.TenantId == null, ct) ?? throw new ResourceConflictException("Technician must be an active platform account."); var r = await Find(id, ct); if (r.Status is not (ServiceRequestStatus.Open or ServiceRequestStatus.Assigned)) throw new ResourceConflictException("Only an Open or Assigned request can be assigned."); var from = r.Status; r.AssignedTechnicianId = tech.Id; r.Status = ServiceRequestStatus.Assigned; Add(r, admin, from == ServiceRequestStatus.Assigned ? ServiceHistoryEventType.Reassigned : ServiceHistoryEventType.Assigned, from, r.Status, c.Notes); await db.SaveChangesAsync(ct); return await Load(id, ct); }
    public async Task<ServiceRequestView> AcceptAsync(Guid tech, Guid id, CancellationToken ct) { var r = await Assigned(tech, id, ct); Move(r, tech, ServiceRequestStatus.Assigned, ServiceRequestStatus.InProgress, ServiceHistoryEventType.Accepted, null); r.AcceptedAtUtc = clock.GetUtcNow().UtcDateTime; await db.SaveChangesAsync(ct); return await Load(id, ct); }
    public async Task<ServiceRequestView> DiagnoseAsync(Guid tech, Guid id, DiagnoseServiceRequestCommand c, CancellationToken ct) { var r = await Assigned(tech, id, ct); Move(r, tech, ServiceRequestStatus.InProgress, ServiceRequestStatus.Diagnosed, ServiceHistoryEventType.Diagnosed, c.Diagnosis); r.InspectionNotes = FinanceService.Required(c.InspectionNotes, "inspectionNotes", 2000); r.Diagnosis = FinanceService.Required(c.Diagnosis, "diagnosis", 2000); r.ResolutionAction = c.ResolutionAction; await db.SaveChangesAsync(ct); return await Load(id, ct); }
    public async Task<ServiceRequestView> RecordWorkAsync(Guid tech, Guid id, RecordServiceWorkCommand c, CancellationToken ct) { var r = await Assigned(tech, id, ct); if (r.ResolutionAction == ServiceResolutionAction.Replacement) throw new ResourceConflictException("Use replacement for a Replacement diagnosis."); Move(r, tech, ServiceRequestStatus.Diagnosed, ServiceRequestStatus.WorkCompleted, ServiceHistoryEventType.WorkRecorded, c.WorkPerformed); r.WorkPerformed = FinanceService.Required(c.WorkPerformed, "workPerformed", 2000); await db.SaveChangesAsync(ct); return await Load(id, ct); }
    public Task<ServiceRequestView> HotSwapAsync(Guid tech, Guid zone, Guid old, Guid request, ReplaceServiceDeviceCommand c, CancellationToken ct) => ReplaceInternal(tech, request, c, zone, old, ct);
    public Task<ServiceRequestView> ReplaceAsync(Guid tech, Guid id, ReplaceServiceDeviceCommand c, CancellationToken ct) => ReplaceInternal(tech, id, c, null, null, ct);
    private async Task<ServiceRequestView> ReplaceInternal(Guid tech, Guid id, ReplaceServiceDeviceCommand c, Guid? routeZone, Guid? routeOld, CancellationToken ct)
    {
        var r = await Assigned(tech, id, ct); if (r.Status != ServiceRequestStatus.Diagnosed || r.ResolutionAction != ServiceResolutionAction.Replacement) throw new ResourceConflictException("Request must be diagnosed for Replacement."); var oldId = r.CurrentDeviceId ?? r.DeviceId ?? throw new ResourceConflictException("Request has no Device."); if (routeZone.HasValue && (r.ZoneId != routeZone || oldId != routeOld)) throw new ResourceNotFoundException("Service Request does not match the old Device and Zone."); var old = await db.Devices.Include(x => x.Sensors).Include(x => x.Actuators).SingleAsync(x => x.Id == oldId, ct); var next = await db.Devices.Include(x => x.Sensors).Include(x => x.Actuators).SingleOrDefaultAsync(x => x.Id == c.NewDeviceId && x.FarmId == r.FarmId && x.Status != DeviceStatus.Decommissioned, ct) ?? throw new ResourceNotFoundException("Replacement Device was not found in this Farm."); if (next.ZoneId.HasValue) throw new ResourceConflictException("Replacement Device is already assigned to a Zone."); if (next.DeviceType != old.DeviceType) throw new ResourceConflictException("Replacement Device type is incompatible.");
        await using var tx = await db.Database.BeginTransactionAsync(ct); db.DeviceSensors.RemoveRange(next.Sensors); db.DeviceActuators.RemoveRange(next.Actuators); foreach (var s in old.Sensors) db.DeviceSensors.Add(new DeviceSensor { DeviceId = next.Id, SensorType = s.SensorType, Pin = s.Pin, Model = s.Model, Interface = s.Interface, Unit = s.Unit, MinValue = s.MinValue, MaxValue = s.MaxValue, SamplingIntervalSec = s.SamplingIntervalSec }); foreach (var a in old.Actuators) db.DeviceActuators.Add(new DeviceActuator { DeviceId = next.Id, ActuatorType = a.ActuatorType, RelayChannel = a.RelayChannel, RatedPowerWatt = a.RatedPowerWatt, FlowRateLitersPerMinute = a.FlowRateLitersPerMinute, MaxDurationMinutes = a.MaxDurationMinutes }); old.ZoneId = null; old.Status = DeviceStatus.Decommissioned; old.DecommissionedAtUtc = clock.GetUtcNow().UtcDateTime; next.ZoneId = r.ZoneId; next.Status = DeviceStatus.Assigned; r.CurrentDeviceId = next.Id; r.Status = ServiceRequestStatus.WorkCompleted; r.WorkPerformed = FinanceService.Optional(c.Notes, 2000) ?? "Device replaced and configuration copied."; db.DeviceReplacements.Add(new DeviceReplacement { ServiceRequest = r, OldDeviceId = old.Id, NewDeviceId = next.Id, ZoneId = r.ZoneId, TechnicianUserId = tech }); db.DeviceAssignmentHistory.AddRange(new DeviceAssignmentHistory { DeviceId = old.Id, ZoneId = r.ZoneId, TechnicianUserId = tech, Action = "ReplacedOut", Notes = c.Notes }, new DeviceAssignmentHistory { DeviceId = next.Id, ZoneId = r.ZoneId, TechnicianUserId = tech, Action = "ReplacedIn", Notes = c.Notes }); Add(r, tech, ServiceHistoryEventType.Replaced, ServiceRequestStatus.Diagnosed, r.Status, c.Notes); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await Load(id, ct);
    }
    public async Task<ServiceRequestView> TestAsync(Guid tech, Guid id, ServiceConnectionTestCommand c, CancellationToken ct)
    { var r = await Assigned(tech, id, ct); if (r.Status is not (ServiceRequestStatus.WorkCompleted or ServiceRequestStatus.Verified)) throw new ResourceConflictException("Complete service work before testing."); if (c.ObservedAtUtc.Kind != DateTimeKind.Utc) throw new RequestValidationException("observedAtUtc", "Observed time must be UTC."); var device = r.CurrentDeviceId ?? r.DeviceId ?? throw new ResourceConflictException("Request has no current Device."); var test = new DeviceConnectionTest { DeviceId = device, DeploymentRequestId = r.DeploymentRequestId, TechnicianUserId = tech, Succeeded = c.Succeeded, Rssi = c.Rssi, Snr = c.Snr, RoundTripLatencyMs = c.RoundTripLatencyMs, ObservedAtUtc = c.ObservedAtUtc, ErrorCode = FinanceService.Optional(c.ErrorCode, 100), ErrorMessage = FinanceService.Optional(c.ErrorMessage, 1000) }; db.DeviceConnectionTests.Add(test); var from = r.Status; r.Status = c.Succeeded ? ServiceRequestStatus.Verified : ServiceRequestStatus.WorkCompleted; Add(r, tech, c.Succeeded ? ServiceHistoryEventType.TestPassed : ServiceHistoryEventType.TestFailed, from, r.Status, c.ErrorMessage); await db.SaveChangesAsync(ct); return await Load(id, ct); }
    public async Task<ServiceRequestView> CloseAsync(Guid tech, Guid id, CancellationToken ct)
    { var r = await Assigned(tech, id, ct); if (r.Status != ServiceRequestStatus.Verified) throw new ResourceConflictException("A successful current-Device connection test is required before closure."); var device = r.CurrentDeviceId ?? r.DeviceId!.Value; var latest = await db.DeviceConnectionTests.Where(x => x.DeviceId == device).OrderByDescending(x => x.ObservedAtUtc).FirstOrDefaultAsync(ct); if (latest?.Succeeded != true) throw new ResourceConflictException("The latest current-Device connection test did not pass."); var from = r.Status; r.Status = ServiceRequestStatus.Closed; r.ClosedAtUtc = clock.GetUtcNow().UtcDateTime; (await db.Devices.SingleAsync(x => x.Id == device, ct)).Status = DeviceStatus.Online; Add(r, tech, ServiceHistoryEventType.Closed, from, r.Status, null); await db.SaveChangesAsync(ct); return await Load(id, ct); }
    private IQueryable<ServiceRequest> Query() => db.ServiceRequests.Include(x => x.History).Include(x => x.Replacements);
    private async Task<ServiceRequest> Find(Guid id, CancellationToken ct) => await Query().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new ResourceNotFoundException("Service Request was not found.");
    private async Task<ServiceRequest> Assigned(Guid tech, Guid id, CancellationToken ct) { await Role(tech, UserRole.PlatformTechnician, ct); var r = await Find(id, ct); if (r.AssignedTechnicianId != tech) throw new AuthorizationException("Only the assigned Technician may update this request."); return r; }
    private async Task<AppUser> User(Guid id, CancellationToken ct) => await db.AppUsers.SingleOrDefaultAsync(x => x.Id == id && x.Status == AccountStatus.Active, ct) ?? throw new AuthorizationException();
    private async Task Role(Guid id, UserRole role, CancellationToken ct) { if (!await db.AppUsers.AnyAsync(x => x.Id == id && x.Role == role && x.Status == AccountStatus.Active, ct)) throw new AuthorizationException(); }
    private async Task OwnerFarm(Guid owner, Guid tenant, Guid farm, CancellationToken ct) { await Role(owner, UserRole.FarmOwner, ct); if (!await db.Farms.AnyAsync(x => x.Id == farm && x.TenantId == tenant && x.ArchivedAtUtc == null, ct)) throw new ResourceNotFoundException("Farm was not found in the authenticated Tenant."); }
    private static void Visible(AppUser u, Guid? tenant, ServiceRequest r) { if (u.Role == UserRole.FarmOwner && (tenant is null || r.TenantId != tenant)) throw new ResourceNotFoundException("Service Request was not found."); if (u.Role == UserRole.PlatformTechnician && r.AssignedTechnicianId != u.Id) throw new ResourceNotFoundException("Service Request was not found."); if (u.Role is not (UserRole.FarmOwner or UserRole.PlatformAdmin or UserRole.PlatformTechnician)) throw new AuthorizationException(); }
    private void Move(ServiceRequest r, Guid actor, ServiceRequestStatus expected, ServiceRequestStatus next, ServiceHistoryEventType e, string? notes) { if (r.Status != expected) throw new ResourceConflictException($"Expected Service Request state {expected}."); var from = r.Status; r.Status = next; Add(r, actor, e, from, next, notes); }
    private void Add(ServiceRequest r, Guid actor, ServiceHistoryEventType e, ServiceRequestStatus from, ServiceRequestStatus to, string? notes) { var h = new ServiceRequestHistory { ServiceRequest = r, ActorUserId = actor, EventType = e, FromStatus = from, ToStatus = to, Notes = FinanceService.Optional(notes, 2000) }; r.History.Add(h); db.ServiceRequestHistories.Add(h); }
    private async Task<ServiceRequestView> Load(Guid id, CancellationToken ct) => View(await Query().AsNoTracking().SingleAsync(x => x.Id == id, ct));
    private static ServiceRequestView View(ServiceRequest r) => new(r.Id, r.TenantId, r.FarmId, r.ZoneId, r.DeviceId, r.CurrentDeviceId ?? r.DeviceId, r.FailureCode, r.Description, r.Status, r.AssignedTechnicianId, r.InspectionNotes, r.Diagnosis, r.ResolutionAction, r.WorkPerformed, r.ClosedAtUtc, r.History.OrderBy(x => x.CreatedAtUtc).Select(x => new ServiceHistoryView(x.Id, x.EventType, x.FromStatus, x.ToStatus, x.ActorUserId, x.Notes, x.CreatedAtUtc)).ToList(), r.Replacements.OrderBy(x => x.CreatedAtUtc).Select(x => new DeviceReplacementView(x.Id, x.OldDeviceId, x.NewDeviceId, x.ZoneId, x.CreatedAtUtc)).ToList());
}
