using System.Data;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using SmartFarm.Application.Common.Exceptions;
using SmartFarm.Application.Common.Interfaces;
using SmartFarm.Application.Features.IoTDeployment;
using SmartFarm.Domain.Entities;
using SmartFarm.Domain.Enums;
using SmartFarm.Infrastructure.Persistence;

namespace SmartFarm.Infrastructure.IoTDeployment;

internal sealed partial class IoTDeploymentService(SmartFarmDbContext db) : IIoTDeploymentService
{
    private static readonly DeploymentRequestStatus[] ActiveStatuses = [DeploymentRequestStatus.Submitted, DeploymentRequestStatus.Accepted, DeploymentRequestStatus.Surveyed, DeploymentRequestStatus.PlanConfirmed, DeploymentRequestStatus.Installing];

    public async Task<IoTRequirementsView> GetRequirementsAsync(Guid ownerId, Guid tenantId, Guid zoneId, CancellationToken ct)
    {
        await EnsureOwnerAsync(ownerId, tenantId, ct);
        var season = await db.PlantingSeasons.AsNoTracking().Include(x => x.Zone).ThenInclude(x => x.Field).ThenInclude(x => x.Farm).Include(x => x.AppliedRequirements).SingleOrDefaultAsync(x => x.ZoneId == zoneId && x.Status == PlantingSeasonStatus.InProgress && x.Zone.Field.Farm.TenantId == tenantId, ct) ?? throw new ResourceNotFoundException("Zone has no InProgress Planting Season in the current Tenant.");
        return new(zoneId, season.Id, season.CurrentGrowthStageId, season.Zone.AreaM2, season.AppliedRequirements.Select(x => x.ParameterCode).Distinct().Order().ToList());
    }

    public async Task<IReadOnlyList<DeviceRecommendationView>> RecommendAsync(Guid ownerId, Guid tenantId, Guid zoneId, CancellationToken ct)
    {
        var requirements = await GetRequirementsAsync(ownerId, tenantId, zoneId, ct);
        var models = await db.DeviceModelDefinitions.AsNoTracking().Include(x => x.Capabilities).Where(x => x.IsActive).ToListAsync(ct);
        var compatible = models.Where(x => requirements.Parameters.All(p => x.Capabilities.Any(c => c.ParameterCode == p))).ToList();
        if (compatible.Count == 0) throw new ResourceConflictException("No active Device Model covers every required environmental parameter.");
        return compatible.Select(x => new DeviceRecommendationView(x.Id, x.Name, x.DeviceType, x.CoverageAreaM2, Math.Max(1, (int)Math.Ceiling(requirements.ZoneAreaM2 / x.CoverageAreaM2)), x.Capabilities.Select(c => c.ParameterCode).Order().ToList())).ToList();
    }

    public async Task<DeploymentRequestView> CreateRequestAsync(Guid ownerId, Guid tenantId, Guid zoneId, CreateDeploymentRequestCommand command, CancellationToken ct)
    {
        var reqs = await GetRequirementsAsync(ownerId, tenantId, zoneId, ct); ValidatePlan(command.Items);
        var zone = await db.Zones.Include(x => x.Field).ThenInclude(x => x.Farm).SingleAsync(x => x.Id == zoneId, ct);
        await ValidateModelsCoverAsync(command.Items, reqs.Parameters, ct);
        var request = new DeploymentRequest { TenantId = tenantId, FarmId = zone.Field.FarmId, ZoneId = zoneId, PlantingSeasonId = reqs.PlantingSeasonId, OwnerUserId = ownerId, Status = DeploymentRequestStatus.Draft, RequiredParametersCsv = string.Join(',', reqs.Parameters), OwnerNotes = Optional(command.Notes, 1000) };
        AddPlan(request, command.Items); db.DeploymentRequests.Add(request); AddDecision(request, ownerId, "DraftCreated", request.Status, request.Status, command.Notes); await db.SaveChangesAsync(ct); return await LoadRequestAsync(request.Id, ct);
    }

    public async Task<DeploymentRequestView> UpdateOwnerPlanAsync(Guid ownerId, Guid tenantId, Guid requestId, IReadOnlyList<PlanItemInput> items, CancellationToken ct)
    {
        await EnsureOwnerAsync(ownerId, tenantId, ct); ValidatePlan(items); var request = await OwnerRequestAsync(ownerId, tenantId, requestId, ct); EnsureStatus(request, DeploymentRequestStatus.Draft); await ValidateModelsCoverAsync(items, Parse(request.RequiredParametersCsv), ct); ReplacePlan(request, items); AddDecision(request, ownerId, "OwnerPlanAdjusted", request.Status, request.Status, null); await db.SaveChangesAsync(ct); return await LoadRequestAsync(request.Id, ct);
    }

    public async Task<DeploymentRequestView> SubmitAsync(Guid ownerId, Guid tenantId, Guid requestId, CancellationToken ct)
    {
        await EnsureOwnerAsync(ownerId, tenantId, ct); var request = await OwnerRequestAsync(ownerId, tenantId, requestId, ct); EnsureStatus(request, DeploymentRequestStatus.Draft); if (request.PlanItems.Count == 0) throw new ResourceConflictException("A Deployment Request requires at least one plan item.");
        await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); if (await db.DeploymentRequests.AnyAsync(x => x.ZoneId == request.ZoneId && x.Id != request.Id && ActiveStatuses.Contains(x.Status), ct)) throw new ResourceConflictException("Zone already has a non-terminal Deployment Request."); Transition(request, ownerId, "Submitted", DeploymentRequestStatus.Submitted, request.OwnerNotes); request.SubmittedAtUtc = DateTime.UtcNow; await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await LoadRequestAsync(request.Id, ct);
    }

    public async Task<DeploymentRequestView> GetRequestAsync(Guid userId, Guid? tenantId, Guid requestId, CancellationToken ct)
    {
        var user = await UserAsync(userId, ct); var request = await LoadRequestEntityAsync(requestId, ct);
        if (user.Role == UserRole.FarmOwner && (tenantId != request.TenantId || user.TenantId != request.TenantId)) throw new ResourceNotFoundException("Deployment Request was not found in the current Tenant.");
        if (user.Role == UserRole.PlatformTechnician && request.TechnicianUserId != userId) throw new ResourceNotFoundException("Deployment Request is not assigned to this Technician.");
        if (user.Role is not (UserRole.FarmOwner or UserRole.PlatformTechnician)) throw new AuthorizationException(); return request.ToView();
    }

    public async Task<IReadOnlyList<DeploymentRequestView>> ListTechnicianRequestsAsync(Guid technicianId, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); return (await RequestQuery().AsNoTracking().Where(x => (x.Status == DeploymentRequestStatus.Submitted && x.TechnicianUserId == null) || x.TechnicianUserId == technicianId).OrderByDescending(x => x.SubmittedAtUtc).ToListAsync(ct)).Select(x => x.ToView()).ToList(); }
    public async Task<DeploymentRequestView> AcceptAsync(Guid technicianId, Guid requestId, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var r = await LoadRequestEntityAsync(requestId, ct); EnsureStatus(r, DeploymentRequestStatus.Submitted); if (r.TechnicianUserId.HasValue) throw new ResourceConflictException("Deployment Request was already accepted."); r.TechnicianUserId = technicianId; Transition(r, technicianId, "Accepted", DeploymentRequestStatus.Accepted, null); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await LoadRequestAsync(r.Id, ct); }
    public async Task<DeploymentRequestView> SurveyAsync(Guid technicianId, Guid requestId, SurveyCommand command, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, requestId, ct); if (r.Status is not (DeploymentRequestStatus.Accepted or DeploymentRequestStatus.Surveyed)) throw new ResourceConflictException("Survey requires an Accepted request."); var survey = new DeploymentSurvey { DeploymentRequestId = r.Id, TechnicianUserId = technicianId, IsFeasible = command.IsFeasible, SiteConditions = Required(command.SiteConditions, "siteConditions", 2000), Notes = Required(command.Notes, "notes", 2000) }; db.DeploymentSurveys.Add(survey); Transition(r, technicianId, command.IsFeasible ? "SurveyFeasible" : "SurveyInfeasible", DeploymentRequestStatus.Surveyed, command.Notes); await db.SaveChangesAsync(ct); return await LoadRequestAsync(r.Id, ct); }
    public async Task<DeploymentRequestView> UpdateTechnicianPlanAsync(Guid technicianId, Guid requestId, IReadOnlyList<PlanItemInput> items, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); ValidatePlan(items); var r = await TechnicianRequestAsync(technicianId, requestId, ct); EnsureStatus(r, DeploymentRequestStatus.Surveyed); await ValidateModelsCoverAsync(items, Parse(r.RequiredParametersCsv), ct); ReplacePlan(r, items); AddDecision(r, technicianId, "TechnicianPlanAdjusted", r.Status, r.Status, null); await db.SaveChangesAsync(ct); return await LoadRequestAsync(r.Id, ct); }
    public async Task<DeploymentRequestView> ConfirmAsync(Guid technicianId, Guid requestId, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, requestId, ct); EnsureStatus(r, DeploymentRequestStatus.Surveyed); if (!r.Surveys.OrderByDescending(x => x.CreatedAtUtc).First().IsFeasible) throw new ResourceConflictException("The latest survey is not feasible."); Transition(r, technicianId, "PlanConfirmed", DeploymentRequestStatus.PlanConfirmed, null); await db.SaveChangesAsync(ct); return await LoadRequestAsync(r.Id, ct); }
    public async Task<DeploymentRequestView> StartInstallationAsync(Guid technicianId, Guid requestId, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, requestId, ct); EnsureStatus(r, DeploymentRequestStatus.PlanConfirmed); Transition(r, technicianId, "InstallationStarted", DeploymentRequestStatus.Installing, null); await db.SaveChangesAsync(ct); return await LoadRequestAsync(r.Id, ct); }

    public async Task<DeviceConnectionTestView> RecordConnectionTestAsync(Guid technicianId, Guid requestId, ConnectionTestCommand command, CancellationToken ct)
    {
        await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, requestId, ct); EnsureStatus(r, DeploymentRequestStatus.Installing); var d = await db.Devices.SingleOrDefaultAsync(x => x.Id == command.DeviceId && x.DeploymentRequestId == requestId && x.ZoneId == r.ZoneId, ct) ?? throw new ResourceNotFoundException("Assigned Device was not found in this deployment Zone.");
        if (command.ObservedAtUtc == default || command.ObservedAtUtc > DateTime.UtcNow.AddMinutes(5)) throw new RequestValidationException("observedAtUtc", "Observed time is required and cannot be in the future."); if (!command.Succeeded && string.IsNullOrWhiteSpace(command.ErrorCode)) throw new RequestValidationException("errorCode", "A failed test requires an error code.");
        var test = new DeviceConnectionTest { DeviceId = d.Id, DeploymentRequestId = r.Id, TechnicianUserId = technicianId, Succeeded = command.Succeeded, Rssi = command.Rssi, Snr = command.Snr, RoundTripLatencyMs = command.RoundTripLatencyMs, ObservedAtUtc = command.ObservedAtUtc.ToUniversalTime(), ErrorCode = Optional(command.ErrorCode, 100), ErrorMessage = Optional(command.ErrorMessage, 1000) }; db.DeviceConnectionTests.Add(test); d.Status = command.Succeeded ? DeviceStatus.Online : DeviceStatus.MaintenanceRequired; AddDecision(r, technicianId, command.Succeeded ? "ConnectionTestPassed" : "ConnectionTestFailed", r.Status, r.Status, command.ErrorCode); await db.SaveChangesAsync(ct); return TestView(test);
    }

    public async Task<DeploymentRequestView> CompleteAsync(Guid technicianId, Guid requestId, CancellationToken ct)
    {
        await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, requestId, ct); EnsureStatus(r, DeploymentRequestStatus.Installing); var devices = await db.Devices.Include(x => x.ConnectionTests).Where(x => x.DeploymentRequestId == r.Id && x.ZoneId == r.ZoneId && x.Status != DeviceStatus.Decommissioned).ToListAsync(ct); var planned = r.PlanItems.Sum(x => x.Quantity); if (devices.Count != planned || devices.Any(x => x.ConnectionTests.OrderByDescending(t => t.ObservedAtUtc).FirstOrDefault()?.Succeeded != true)) throw new ResourceConflictException("Every planned Device must be assigned and have a successful latest connection test."); Transition(r, technicianId, "DeploymentCompleted", DeploymentRequestStatus.Completed, null); r.CompletedAtUtc = DateTime.UtcNow; await db.SaveChangesAsync(ct); return await LoadRequestAsync(r.Id, ct);
    }

    public async Task<ServiceHandoffView> FailAsync(Guid technicianId, Guid requestId, FailDeploymentCommand command, CancellationToken ct)
    {
        await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, requestId, ct); if (r.Status is DeploymentRequestStatus.Completed or DeploymentRequestStatus.MaintenanceRequired) throw new ResourceConflictException("Deployment is already terminal."); var code = Required(command.FailureCode, "failureCode", 100); var description = Required(command.Description, "description", 2000); if (command.DeviceId.HasValue && !await db.Devices.AnyAsync(x => x.Id == command.DeviceId && x.DeploymentRequestId == requestId, ct)) throw new ResourceNotFoundException("Device was not found in this Deployment Request."); await using var tx = await db.Database.BeginTransactionAsync(ct); r.FailureCode = code; r.FailureDescription = description; Transition(r, technicianId, "DeploymentFailed", DeploymentRequestStatus.MaintenanceRequired, description); var affected = await db.Devices.Where(x => x.DeploymentRequestId == requestId && (!command.DeviceId.HasValue || x.Id == command.DeviceId)).ToListAsync(ct); foreach (var d in affected) d.Status = DeviceStatus.MaintenanceRequired; var service = new ServiceRequest { TenantId = r.TenantId, FarmId = r.FarmId, ZoneId = r.ZoneId, DeploymentRequestId = r.Id, DeviceId = command.DeviceId, Source = "DeploymentFailure", FailureCode = code, Description = description }; db.ServiceRequests.Add(service); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(service.Id, r.Id, service.Status);
    }

    public async Task<IReadOnlyList<GatewayView>> ListGatewaysAsync(Guid userId, Guid? tenantId, Guid farmId, CancellationToken ct) { await EnsureFarmReadAsync(userId, tenantId, farmId, ct); return (await db.Gateways.AsNoTracking().Include(x => x.Devices).Where(x => x.FarmId == farmId).ToListAsync(ct)).Select(x => x.ToView()).ToList(); }
    public async Task<GatewayView> ProvisionGatewayAsync(Guid technicianId, ProvisionGatewayCommand command, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var r = await TechnicianRequestAsync(technicianId, command.DeploymentRequestId, ct); EnsureStatus(r, DeploymentRequestStatus.Installing); if (r.FarmId != command.FarmId) throw new RequestValidationException("farmId", "Farm does not match the accepted Deployment Request."); if (!MacRegex().IsMatch(command.MacAddress)) throw new RequestValidationException("macAddress", "MAC address must use XX:XX:XX:XX:XX:XX format."); var mqttClientId = Required(command.MqttClientId, "mqttClientId", 150); var fingerprint = Required(command.ClientCertificateFingerprint, "clientCertificateFingerprint", 128).Replace(":", "", StringComparison.Ordinal).ToUpperInvariant(); if (fingerprint.Length != 64 || fingerprint.Any(c => !Uri.IsHexDigit(c))) throw new RequestValidationException("clientCertificateFingerprint", "Certificate fingerprint must be a SHA-256 hexadecimal value."); if (await db.Gateways.AnyAsync(x => x.MacAddress == command.MacAddress || x.GatewaySerial == command.GatewaySerial || x.MqttClientId == mqttClientId || x.ClientCertificateFingerprint == fingerprint, ct)) throw new ResourceConflictException("Gateway MAC, serial, MQTT client ID or certificate is already registered."); var gateway = new Gateway { DeploymentRequestId = r.Id, FarmId = r.FarmId, MacAddress = command.MacAddress.ToUpperInvariant(), GatewaySerial = Required(command.GatewaySerial, "gatewaySerial", 100), FrequencyBand = Required(command.FrequencyBand, "frequencyBand", 30), FirmwareVersion = Required(command.FirmwareVersion, "firmwareVersion", 50), MqttClientId = mqttClientId, ClientCertificateFingerprint = fingerprint }; db.Gateways.Add(gateway); AddDecision(r, technicianId, "GatewayProvisioned", r.Status, r.Status, gateway.GatewaySerial); await db.SaveChangesAsync(ct); return gateway.ToView(); }
    public async Task<GatewayView> GetGatewayAsync(Guid userId, Guid? tenantId, Guid gatewayId, CancellationToken ct) { var g = await db.Gateways.AsNoTracking().Include(x => x.Devices).Include(x => x.Farm).SingleOrDefaultAsync(x => x.Id == gatewayId, ct) ?? throw new ResourceNotFoundException("Gateway was not found."); await EnsureHardwareReadAsync(userId, tenantId, g.Farm.TenantId, g.DeploymentRequestId, ct); return g.ToView(); }
    public async Task<FirmwareJobView> ScheduleFirmwareAsync(Guid technicianId, Guid gatewayId, FirmwareCommand command, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var g = await TechnicianGatewayAsync(technicianId, gatewayId, ct); if (await db.FirmwareJobs.AnyAsync(x => x.GatewayId == gatewayId && (x.Status == FirmwareJobStatus.Scheduled || x.Status == FirmwareJobStatus.InProgress), ct)) throw new ResourceConflictException("Gateway already has an active firmware job."); var job = new FirmwareJob { GatewayId = g.Id, TargetVersion = Required(command.TargetVersion, "targetVersion", 50), FirmwareUrl = Required(command.FirmwareUrl, "firmwareUrl", 1000), ScheduledAtUtc = command.ScheduledAtUtc.ToUniversalTime() }; db.FirmwareJobs.Add(job); await db.SaveChangesAsync(ct); return new(job.Id, g.Id, job.TargetVersion, job.ScheduledAtUtc, job.Status); }
    public async Task<IReadOnlyList<DeviceView>> ListFarmDevicesAsync(Guid userId, Guid? tenantId, Guid farmId, CancellationToken ct) { await EnsureFarmReadAsync(userId, tenantId, farmId, ct); return (await DeviceQuery().AsNoTracking().Where(x => x.FarmId == farmId && x.Status != DeviceStatus.Decommissioned).ToListAsync(ct)).Select(x => x.ToView()).ToList(); }
    public async Task<IReadOnlyList<DeviceView>> ListZoneDevicesAsync(Guid ownerId, Guid tenantId, Guid zoneId, CancellationToken ct) { await EnsureOwnerAsync(ownerId, tenantId, ct); if (!await db.Zones.AnyAsync(x => x.Id == zoneId && x.Field.Farm.TenantId == tenantId, ct)) throw new ResourceNotFoundException("Zone was not found in the current Tenant."); return (await DeviceQuery().AsNoTracking().Where(x => x.ZoneId == zoneId && x.Status != DeviceStatus.Decommissioned).ToListAsync(ct)).Select(x => x.ToView()).ToList(); }
    public async Task<DeviceView> GetDeviceAsync(Guid userId, Guid? tenantId, Guid deviceId, CancellationToken ct) { var d = await DeviceQuery().AsNoTracking().Include(x => x.Farm).SingleOrDefaultAsync(x => x.Id == deviceId, ct) ?? throw new ResourceNotFoundException("Device was not found."); await EnsureHardwareReadAsync(userId, tenantId, d.Farm.TenantId, d.DeploymentRequestId, ct); return d.ToView(); }

    public async Task<ProvisionDevicesView> ProvisionDevicesAsync(Guid technicianId, ProvisionDevicesCommand command, CancellationToken ct)
    {
        await EnsureTechnicianAsync(technicianId, ct); if (command.Nodes.Count is < 1 or > 50) throw new RequestValidationException("nodes", "Provide between 1 and 50 nodes."); if (command.Nodes.Select(x => x.HardwareAddress.ToUpperInvariant()).Distinct().Count() != command.Nodes.Count) throw new RequestValidationException("nodes", "Hardware addresses must be unique."); var r = await TechnicianRequestAsync(technicianId, command.DeploymentRequestId, ct); EnsureStatus(r, DeploymentRequestStatus.Installing); var g = await db.Gateways.SingleOrDefaultAsync(x => x.Id == command.GatewayId && x.DeploymentRequestId == r.Id && x.FarmId == r.FarmId, ct) ?? throw new ResourceNotFoundException("Gateway was not found in this Deployment Request."); if (command.FarmId != r.FarmId) throw new RequestValidationException("farmId", "Farm does not match the Deployment Request."); var addresses = command.Nodes.Select(x => x.HardwareAddress.Trim().ToUpperInvariant()).ToList(); if (await db.Devices.AnyAsync(x => addresses.Contains(x.HardwareAddress), ct)) throw new ResourceConflictException("A hardware address is already provisioned."); var modelIds = command.Nodes.Where(x => x.DeviceModelId.HasValue).Select(x => x.DeviceModelId!.Value).Distinct().ToList(); if (await db.DeviceModelDefinitions.CountAsync(x => modelIds.Contains(x.Id) && x.IsActive, ct) != modelIds.Count) throw new RequestValidationException("deviceModelId", "One or more Device Models are invalid."); var devices = command.Nodes.Select(x => new Device { FarmId = r.FarmId, GatewayId = g.Id, DeploymentRequestId = r.Id, HardwareAddress = x.HardwareAddress.Trim().ToUpperInvariant(), DeviceType = x.DeviceType, DeviceModelDefinitionId = x.DeviceModelId }).ToList(); db.Devices.AddRange(devices); AddDecision(r, technicianId, "DevicesProvisioned", r.Status, r.Status, $"Count={devices.Count}"); await db.SaveChangesAsync(ct); return new(devices.Count, devices.Select(x => x.ToView()).ToList());
    }

    public async Task<DeviceView> ConfigureSensorsAsync(Guid technicianId, Guid deviceId, IReadOnlyList<SensorInput> sensors, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var d = await TechnicianDeviceAsync(technicianId, deviceId, ct); if (d.DeviceType != DeviceType.SensorNode) throw new ResourceConflictException("Only a SensorNode accepts sensor configuration."); if (sensors.Count == 0 || sensors.Any(x => x.SamplingIntervalSec is < 10 or > 3600) || sensors.Where(x => x.Pin != null).GroupBy(x => x.Pin).Any(g => g.Count() > 1)) throw new RequestValidationException("sensors", "Sensors require unique pins and sampling interval 10–3600 seconds."); db.DeviceSensors.RemoveRange(d.Sensors); var rows = sensors.Select(x => new DeviceSensor { DeviceId = d.Id, SensorType = Required(x.SensorType, "sensorType", 50), Pin = Optional(x.Pin, 30), Model = Optional(x.Model, 100), Interface = Optional(x.Interface, 30), Unit = Required(x.Unit, "unit", 30), MinValue = x.MinValue, MaxValue = x.MaxValue, SamplingIntervalSec = x.SamplingIntervalSec }).ToList(); db.DeviceSensors.AddRange(rows); d.Status = DeviceStatus.SensorsConfigured; await db.SaveChangesAsync(ct); return await LoadDeviceAsync(d.Id, ct); }
    public async Task<DeviceView> ConfigureActuatorsAsync(Guid technicianId, Guid deviceId, IReadOnlyList<ActuatorInput> actuators, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var d = await TechnicianDeviceAsync(technicianId, deviceId, ct); if (d.DeviceType != DeviceType.ActuatorNode) throw new ResourceConflictException("Only an ActuatorNode accepts actuator configuration."); if (actuators.Count == 0 || actuators.Any(x => x.RelayChannel is < 1 or > 8 || x.MaxDurationMinutes is < 1 or > 30 || x.RatedPowerWatt is <= 0 || x.FlowRateLitersPerMinute is <= 0) || actuators.GroupBy(x => x.RelayChannel).Any(g => g.Count() > 1)) throw new RequestValidationException("actuators", "Relay channels must be unique (1–8), duration must be 1–30 minutes, and optional power/flow ratings must be positive."); db.DeviceActuators.RemoveRange(d.Actuators); db.DeviceActuators.AddRange(actuators.Select(x => new DeviceActuator { DeviceId = d.Id, ActuatorType = Required(x.ActuatorType, "actuatorType", 50), RelayChannel = x.RelayChannel, RatedPowerWatt = x.RatedPowerWatt, FlowRateLitersPerMinute = x.FlowRateLitersPerMinute, MaxDurationMinutes = x.MaxDurationMinutes })); d.Status = DeviceStatus.ActuatorsConfigured; await db.SaveChangesAsync(ct); return await LoadDeviceAsync(d.Id, ct); }
    public async Task<DeviceView> AssignAsync(Guid technicianId, Guid zoneId, Guid deviceId, AssignDeviceCommand command, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var d = await TechnicianDeviceAsync(technicianId, deviceId, ct); var r = await TechnicianRequestAsync(technicianId, d.DeploymentRequestId, ct); EnsureStatus(r, DeploymentRequestStatus.Installing); if (r.ZoneId != zoneId || d.FarmId != r.FarmId) throw new ResourceNotFoundException("Zone is outside the Device Deployment Request."); if (d.ZoneId.HasValue || d.Status is DeviceStatus.Assigned or DeviceStatus.Online or DeviceStatus.Offline) throw new ResourceConflictException("Device is already assigned."); if (d.DeviceModelDefinitionId is null || !r.PlanItems.Any(x => x.DeviceModelDefinitionId == d.DeviceModelDefinitionId)) throw new ResourceConflictException("Device Model is not in the confirmed deployment plan."); var assignedCount = await db.Devices.CountAsync(x => x.DeploymentRequestId == r.Id && x.ZoneId == zoneId && x.DeviceModelDefinitionId == d.DeviceModelDefinitionId, ct); var planned = r.PlanItems.Single(x => x.DeviceModelDefinitionId == d.DeviceModelDefinitionId).Quantity; if (assignedCount >= planned) throw new ResourceConflictException("Confirmed quantity for this Device Model is already assigned."); d.ZoneId = zoneId; d.Status = DeviceStatus.Assigned; d.InstallationNotes = Optional(command.InstallationNotes, 1000); ValidateGps(command.GpsLatitude, command.GpsLongitude); d.GpsLatitude = command.GpsLatitude; d.GpsLongitude = command.GpsLongitude; var history = new DeviceAssignmentHistory { DeviceId = d.Id, ZoneId = zoneId, TechnicianUserId = technicianId, Action = "Assigned", Notes = d.InstallationNotes }; db.DeviceAssignmentHistory.Add(history); AddDecision(r, technicianId, "DeviceAssigned", r.Status, r.Status, d.HardwareAddress); await db.SaveChangesAsync(ct); return await LoadDeviceAsync(d.Id, ct); }
    public async Task<DeviceView> UnassignAsync(Guid technicianId, Guid zoneId, Guid deviceId, UnassignDeviceCommand command, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var d = await TechnicianDeviceAsync(technicianId, deviceId, ct); if (d.ZoneId != zoneId) throw new ResourceNotFoundException("Device is not assigned to this Zone."); var reason = Required(command.Reason, "reason", 1000); db.DeviceAssignmentHistory.Add(new DeviceAssignmentHistory { DeviceId = d.Id, ZoneId = zoneId, TechnicianUserId = technicianId, Action = "Unassigned", Notes = reason }); d.ZoneId = null; d.Status = DeviceStatus.Unassigned; await db.SaveChangesAsync(ct); return await LoadDeviceAsync(d.Id, ct); }
    public async Task<DeviceConnectionTestView> GetLatestConnectionTestAsync(Guid technicianId, Guid deviceId, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); await TechnicianDeviceAsync(technicianId, deviceId, ct); var t = await db.DeviceConnectionTests.AsNoTracking().Where(x => x.DeviceId == deviceId).OrderByDescending(x => x.ObservedAtUtc).FirstOrDefaultAsync(ct) ?? throw new ResourceNotFoundException("No connection test has been recorded for this Device."); return TestView(t); }
    public async Task<DiagnosticJobView> DiagnoseAsync(Guid technicianId, Guid deviceId, DiagnoseCommand command, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var d = await TechnicianDeviceAsync(technicianId, deviceId, ct); var allowed = new[] { "REBOOT_NODE", "CHANGE_CHANNEL", "REBOOT_AND_CHANGE_CHANNEL", "CALIBRATE_SENSOR", "FACTORY_RESET" }; if (!allowed.Contains(command.Action)) throw new RequestValidationException("action", "Unsupported diagnostic action."); var r = await TechnicianRequestAsync(technicianId, d.DeploymentRequestId, ct); var job = new DeviceDiagnosticJob { DeviceId = d.Id, TechnicianUserId = technicianId, Action = command.Action, NewFrequencyChannel = command.NewFrequencyChannel, IncreaseTxPowerDbm = command.IncreaseTxPowerDbm }; db.DeviceDiagnosticJobs.Add(job); AddDecision(r, technicianId, "DiagnosticQueued", r.Status, r.Status, command.Action); await db.SaveChangesAsync(ct); return new(job.Id, d.Id, job.Action, job.Status, job.CreatedAtUtc); }
    public async Task DecommissionAsync(Guid technicianId, Guid deviceId, CancellationToken ct) { await EnsureTechnicianAsync(technicianId, ct); var d = await TechnicianDeviceAsync(technicianId, deviceId, ct); if (d.ZoneId.HasValue || d.Status != DeviceStatus.Unassigned) throw new ResourceConflictException("Only an Unassigned Device can be decommissioned."); d.Status = DeviceStatus.Decommissioned; d.DecommissionedAtUtc = DateTime.UtcNow; await db.SaveChangesAsync(ct); }

    private IQueryable<DeploymentRequest> RequestQuery() => db.DeploymentRequests.Include(x => x.PlanItems).ThenInclude(x => x.DeviceModelDefinition).Include(x => x.Surveys).Include(x => x.Decisions);
    private IQueryable<Device> DeviceQuery() => db.Devices.Include(x => x.Sensors).Include(x => x.Actuators).Include(x => x.ConnectionTests);
    private async Task<DeploymentRequest> LoadRequestEntityAsync(Guid id, CancellationToken ct) => await RequestQuery().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new ResourceNotFoundException("Deployment Request was not found.");
    private async Task<DeploymentRequestView> LoadRequestAsync(Guid id, CancellationToken ct) { db.ChangeTracker.Clear(); return (await RequestQuery().AsNoTracking().SingleAsync(x => x.Id == id, ct)).ToView(); }
    private async Task<DeviceView> LoadDeviceAsync(Guid id, CancellationToken ct) { db.ChangeTracker.Clear(); return (await DeviceQuery().AsNoTracking().SingleAsync(x => x.Id == id, ct)).ToView(); }
    private async Task<DeploymentRequest> OwnerRequestAsync(Guid owner, Guid tenant, Guid id, CancellationToken ct) => await RequestQuery().SingleOrDefaultAsync(x => x.Id == id && x.OwnerUserId == owner && x.TenantId == tenant, ct) ?? throw new ResourceNotFoundException("Deployment Request was not found in the current Tenant.");
    private async Task<DeploymentRequest> TechnicianRequestAsync(Guid tech, Guid id, CancellationToken ct) => await RequestQuery().SingleOrDefaultAsync(x => x.Id == id && x.TechnicianUserId == tech, ct) ?? throw new ResourceNotFoundException("Deployment Request is not assigned to this Technician.");
    private async Task<Gateway> TechnicianGatewayAsync(Guid tech, Guid id, CancellationToken ct) => await db.Gateways.Include(x => x.Devices).SingleOrDefaultAsync(x => x.Id == id && x.DeploymentRequest.TechnicianUserId == tech, ct) ?? throw new ResourceNotFoundException("Gateway was not found for this Technician.");
    private async Task<Device> TechnicianDeviceAsync(Guid tech, Guid id, CancellationToken ct) => await DeviceQuery().SingleOrDefaultAsync(x => x.Id == id && x.DeploymentRequest.TechnicianUserId == tech, ct) ?? throw new ResourceNotFoundException("Device was not found for this Technician.");
    private async Task EnsureOwnerAsync(Guid id, Guid tenant, CancellationToken ct) { if (!await db.AppUsers.AnyAsync(x => x.Id == id && x.Role == UserRole.FarmOwner && x.TenantId == tenant, ct)) throw new AuthorizationException("FarmOwner role in the current Tenant is required."); }
    private async Task EnsureTechnicianAsync(Guid id, CancellationToken ct) { if (!await db.AppUsers.AnyAsync(x => x.Id == id && x.Role == UserRole.PlatformTechnician && x.TenantId == null, ct)) throw new AuthorizationException("PlatformTechnician role is required."); }
    private async Task<AppUser> UserAsync(Guid id, CancellationToken ct) => await db.AppUsers.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new AuthorizationException();
    private async Task EnsureFarmReadAsync(Guid userId, Guid? tenantId, Guid farmId, CancellationToken ct) { var user = await UserAsync(userId, ct); if (user.Role == UserRole.FarmOwner) { if (!await db.Farms.AnyAsync(x => x.Id == farmId && x.TenantId == tenantId && user.TenantId == tenantId, ct)) throw new ResourceNotFoundException("Farm was not found in the current Tenant."); } else if (user.Role == UserRole.PlatformTechnician) { if (!await db.DeploymentRequests.AnyAsync(x => x.FarmId == farmId && x.TechnicianUserId == userId, ct)) throw new ResourceNotFoundException("Farm has no Deployment Request assigned to this Technician."); } else throw new AuthorizationException(); }
    private async Task EnsureHardwareReadAsync(Guid userId, Guid? tenantId, Guid resourceTenant, Guid requestId, CancellationToken ct) { var user = await UserAsync(userId, ct); if (user.Role == UserRole.FarmOwner && (tenantId != resourceTenant || user.TenantId != resourceTenant)) throw new ResourceNotFoundException("Hardware was not found in the current Tenant."); if (user.Role == UserRole.PlatformTechnician && !await db.DeploymentRequests.AnyAsync(x => x.Id == requestId && x.TechnicianUserId == userId, ct)) throw new ResourceNotFoundException("Hardware is not assigned to this Technician."); if (user.Role is not (UserRole.FarmOwner or UserRole.PlatformTechnician)) throw new AuthorizationException(); }
    private async Task ValidateModelsCoverAsync(IReadOnlyList<PlanItemInput> items, IReadOnlyList<EnvironmentalParameterCode> required, CancellationToken ct) { var ids = items.Select(x => x.DeviceModelId).Distinct().ToList(); var models = await db.DeviceModelDefinitions.Include(x => x.Capabilities).Where(x => ids.Contains(x.Id) && x.IsActive).ToListAsync(ct); if (models.Count != ids.Count) throw new RequestValidationException("items", "One or more Device Models are invalid."); var covered = models.SelectMany(x => x.Capabilities).Select(x => x.ParameterCode).Distinct(); if (required.Except(covered).Any()) throw new RequestValidationException("items", "The plan does not cover every required environmental parameter."); }
    private static void ValidatePlan(IReadOnlyList<PlanItemInput> items) { if (items.Count == 0 || items.Any(x => x.Quantity is < 1 or > 100) || items.Select(x => x.DeviceModelId).Distinct().Count() != items.Count) throw new RequestValidationException("items", "Plan items must be non-empty, unique by model and quantity 1–100."); }
    private void ReplacePlan(DeploymentRequest r, IReadOnlyList<PlanItemInput> items) { db.DeploymentPlanItems.RemoveRange(r.PlanItems); foreach (var old in r.PlanItems.ToList()) r.PlanItems.Remove(old); AddPlan(r, items); }
    private void AddPlan(DeploymentRequest r, IEnumerable<PlanItemInput> items) { foreach (var x in items) { var item = new DeploymentPlanItem { DeploymentRequestId = r.Id, DeviceModelDefinitionId = x.DeviceModelId, Quantity = x.Quantity, InstallationNotes = Optional(x.InstallationNotes, 1000) }; r.PlanItems.Add(item); if (db.Entry(r).State != EntityState.Detached && db.Entry(r).State != EntityState.Added) db.DeploymentPlanItems.Add(item); } }
    private void AddDecision(DeploymentRequest r, Guid actor, string type, DeploymentRequestStatus from, DeploymentRequestStatus to, string? notes) { var d = new DeploymentDecisionHistory { DeploymentRequestId = r.Id, ActorUserId = actor, DecisionType = type, FromStatus = from.ToString(), ToStatus = to.ToString(), Notes = Optional(notes, 2000) }; r.Decisions.Add(d); if (db.Entry(r).State != EntityState.Detached && db.Entry(r).State != EntityState.Added) db.DeploymentDecisionHistory.Add(d); }
    private void Transition(DeploymentRequest r, Guid actor, string type, DeploymentRequestStatus next, string? notes) { var old = r.Status; r.Status = next; AddDecision(r, actor, type, old, next, notes); }
    private static void EnsureStatus(DeploymentRequest r, DeploymentRequestStatus expected) { if (r.Status != expected) throw new ResourceConflictException($"Deployment Request must be {expected}; current status is {r.Status}."); }
    private static IReadOnlyList<EnvironmentalParameterCode> Parse(string csv) => csv.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(Enum.Parse<EnvironmentalParameterCode>).ToList();
    private static DeviceConnectionTestView TestView(DeviceConnectionTest x) => new(x.Id, x.Succeeded, x.Rssi, x.Snr, x.RoundTripLatencyMs, x.ObservedAtUtc, x.ErrorCode, x.ErrorMessage);
    private static string Required(string? value, string field, int max) { var x = value?.Trim(); if (string.IsNullOrWhiteSpace(x) || x.Length > max) throw new RequestValidationException(field, $"Value is required and limited to {max} characters."); return x; }
    private static string? Optional(string? value, int max) { if (string.IsNullOrWhiteSpace(value)) return null; var x = value.Trim(); if (x.Length > max) throw new RequestValidationException("value", $"Value is limited to {max} characters."); return x; }
    private static void ValidateGps(decimal? lat, decimal? lng) { if (lat is < -90 or > 90 || lng is < -180 or > 180 || lat.HasValue != lng.HasValue) throw new RequestValidationException("gps", "Latitude and longitude must be supplied together and within valid ranges."); }
    [GeneratedRegex("^[0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5}$")] private static partial Regex MacRegex();
}
