using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SmartFarm.Domain.Entities;

namespace SmartFarm.Infrastructure.Persistence.Configurations;

internal static class InventoryTaskConfig
{
    internal static void Base<T>(EntityTypeBuilder<T> b) where T : SmartFarm.Domain.Common.AuditableEntity { b.HasKey(x => x.Id); b.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); b.Property(x => x.UpdatedAtUtc).HasColumnName("updated_at_utc"); }
}
internal sealed class InventoryItemConfiguration : IEntityTypeConfiguration<InventoryItem>
{
    public void Configure(EntityTypeBuilder<InventoryItem> b) { b.ToTable("inventory_items", t => { t.HasCheckConstraint("ck_inventory_quantity", "quantity_on_hand >= 0"); t.HasCheckConstraint("ck_inventory_low_threshold", "low_stock_threshold >= 0"); }); InventoryTaskConfig.Base(b); b.Property(x=>x.TenantId).HasColumnName("tenant_id"); b.Property(x=>x.FarmId).HasColumnName("farm_id"); b.Property(x=>x.Name).HasColumnName("name").HasMaxLength(160); b.Property(x=>x.NormalizedName).HasColumnName("normalized_name").HasMaxLength(160); b.Property(x=>x.MaterialType).HasColumnName("material_type").HasConversion<string>().HasMaxLength(30); b.Property(x=>x.Unit).HasColumnName("unit").HasMaxLength(30); b.Property(x=>x.QuantityOnHand).HasColumnName("quantity_on_hand").HasPrecision(18,3); b.Property(x=>x.LowStockThreshold).HasColumnName("low_stock_threshold").HasPrecision(18,3); b.Property(x=>x.ArchivedAtUtc).HasColumnName("archived_at_utc"); b.HasIndex(x=>new{x.FarmId,x.NormalizedName}).IsUnique(); b.HasOne<Tenant>().WithMany().HasForeignKey(x=>x.TenantId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x=>x.Farm).WithMany().HasForeignKey(x=>x.FarmId).OnDelete(DeleteBehavior.Restrict); }
}
internal sealed class MaterialRequirementLinkConfiguration : IEntityTypeConfiguration<MaterialRequirementLink>
{
    public void Configure(EntityTypeBuilder<MaterialRequirementLink> b) { b.ToTable("material_requirement_links", t=>t.HasCheckConstraint("ck_material_requirement_one_target", "(CASE WHEN crop_id IS NULL THEN 0 ELSE 1 END + CASE WHEN variety_id IS NULL THEN 0 ELSE 1 END + CASE WHEN growth_stage_id IS NULL THEN 0 ELSE 1 END) = 1")); InventoryTaskConfig.Base(b); b.Property(x=>x.InventoryItemId).HasColumnName("inventory_item_id"); b.Property(x=>x.CropId).HasColumnName("crop_id"); b.Property(x=>x.VarietyId).HasColumnName("variety_id"); b.Property(x=>x.GrowthStageId).HasColumnName("growth_stage_id"); b.Property(x=>x.RecommendedQuantity).HasColumnName("recommended_quantity").HasPrecision(18,3); b.Property(x=>x.Notes).HasColumnName("notes").HasMaxLength(500); b.HasOne(x=>x.InventoryItem).WithMany(x=>x.Requirements).HasForeignKey(x=>x.InventoryItemId).OnDelete(DeleteBehavior.Cascade); b.HasOne<Crop>().WithMany().HasForeignKey(x=>x.CropId).OnDelete(DeleteBehavior.Restrict); b.HasOne<CropVariety>().WithMany().HasForeignKey(x=>x.VarietyId).OnDelete(DeleteBehavior.Restrict); b.HasOne<GrowthStage>().WithMany().HasForeignKey(x=>x.GrowthStageId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x=>new{x.InventoryItemId,x.CropId,x.VarietyId,x.GrowthStageId}).IsUnique(); }
}
internal sealed class InventoryTransactionConfiguration : IEntityTypeConfiguration<InventoryTransaction>
{
    public void Configure(EntityTypeBuilder<InventoryTransaction> b) { b.ToTable("inventory_transactions",t=>t.HasCheckConstraint("ck_inventory_transaction_quantity","quantity > 0")); InventoryTaskConfig.Base(b); b.Property(x=>x.TenantId).HasColumnName("tenant_id"); b.Property(x=>x.FarmId).HasColumnName("farm_id"); b.Property(x=>x.InventoryItemId).HasColumnName("inventory_item_id"); b.Property(x=>x.MovementType).HasColumnName("movement_type").HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Quantity).HasColumnName("quantity").HasPrecision(18,3); b.Property(x=>x.BalanceAfter).HasColumnName("balance_after").HasPrecision(18,3); b.Property(x=>x.ActorUserId).HasColumnName("actor_user_id"); b.Property(x=>x.ZoneId).HasColumnName("zone_id"); b.Property(x=>x.FarmTaskId).HasColumnName("farm_task_id"); b.Property(x=>x.Notes).HasColumnName("notes").HasMaxLength(500); b.HasOne<Tenant>().WithMany().HasForeignKey(x=>x.TenantId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Farm>().WithMany().HasForeignKey(x=>x.FarmId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x=>x.InventoryItem).WithMany().HasForeignKey(x=>x.InventoryItemId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AppUser>().WithMany().HasForeignKey(x=>x.ActorUserId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Zone>().WithMany().HasForeignKey(x=>x.ZoneId).OnDelete(DeleteBehavior.Restrict); b.HasOne<FarmTask>().WithMany().HasForeignKey(x=>x.FarmTaskId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x=>new{x.InventoryItemId,x.CreatedAtUtc}); }
}
internal sealed class LowStockAlertConfiguration : IEntityTypeConfiguration<LowStockAlert>
{
    public void Configure(EntityTypeBuilder<LowStockAlert> b) { b.ToTable("low_stock_alerts"); InventoryTaskConfig.Base(b); b.Property(x=>x.TenantId).HasColumnName("tenant_id"); b.Property(x=>x.FarmId).HasColumnName("farm_id"); b.Property(x=>x.InventoryItemId).HasColumnName("inventory_item_id"); b.Property(x=>x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(20); b.Property(x=>x.QuantityAtOpen).HasColumnName("quantity_at_open").HasPrecision(18,3); b.Property(x=>x.OpenedAtUtc).HasColumnName("opened_at_utc"); b.Property(x=>x.ResolvedAtUtc).HasColumnName("resolved_at_utc"); b.HasOne<Tenant>().WithMany().HasForeignKey(x=>x.TenantId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Farm>().WithMany().HasForeignKey(x=>x.FarmId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x=>x.InventoryItem).WithMany().HasForeignKey(x=>x.InventoryItemId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x=>x.InventoryItemId).HasFilter("status = 'Open'").IsUnique(); }
}
internal sealed class FarmTaskConfiguration : IEntityTypeConfiguration<FarmTask>
{
    public void Configure(EntityTypeBuilder<FarmTask> b) { b.ToTable("farm_tasks"); InventoryTaskConfig.Base(b); b.Property(x=>x.TenantId).HasColumnName("tenant_id"); b.Property(x=>x.FarmId).HasColumnName("farm_id"); b.Property(x=>x.ZoneId).HasColumnName("zone_id"); b.Property(x=>x.Title).HasColumnName("title").HasMaxLength(200); b.Property(x=>x.Description).HasColumnName("description").HasMaxLength(2000); b.Property(x=>x.Requirements).HasColumnName("requirements").HasMaxLength(2000); b.Property(x=>x.DueAtUtc).HasColumnName("due_at_utc"); b.Property(x=>x.AssignedFarmerId).HasColumnName("assigned_farmer_id"); b.Property(x=>x.CreatedByOwnerId).HasColumnName("created_by_owner_id"); b.Property(x=>x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(30); b.Property(x=>x.Result).HasColumnName("result").HasMaxLength(2000); b.Property(x=>x.FailureReason).HasColumnName("failure_reason").HasMaxLength(2000); b.Property(x=>x.AcceptedAtUtc).HasColumnName("accepted_at_utc"); b.Property(x=>x.StartedAtUtc).HasColumnName("started_at_utc"); b.Property(x=>x.SubmittedAtUtc).HasColumnName("submitted_at_utc"); b.Property(x=>x.ApprovedAtUtc).HasColumnName("approved_at_utc"); b.Property(x=>x.AssignmentVersion).HasColumnName("assignment_version"); b.HasOne(x=>x.Zone).WithMany().HasForeignKey(x=>x.ZoneId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x=>x.AssignedFarmer).WithMany().HasForeignKey(x=>x.AssignedFarmerId).OnDelete(DeleteBehavior.Restrict); b.HasOne<AppUser>().WithMany().HasForeignKey(x=>x.CreatedByOwnerId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x=>new{x.FarmId,x.Status,x.DueAtUtc}); }
}
internal sealed class FarmTaskHistoryConfiguration : IEntityTypeConfiguration<FarmTaskHistory>
{
    public void Configure(EntityTypeBuilder<FarmTaskHistory> b) { b.ToTable("farm_task_history"); InventoryTaskConfig.Base(b); b.Property(x=>x.FarmTaskId).HasColumnName("farm_task_id"); b.Property(x=>x.ActorUserId).HasColumnName("actor_user_id"); b.Property(x=>x.EventType).HasColumnName("event_type").HasConversion<string>().HasMaxLength(30); b.Property(x=>x.FromStatus).HasColumnName("from_status").HasConversion<string>().HasMaxLength(30); b.Property(x=>x.ToStatus).HasColumnName("to_status").HasConversion<string>().HasMaxLength(30); b.Property(x=>x.PreviousAssigneeId).HasColumnName("previous_assignee_id"); b.Property(x=>x.NewAssigneeId).HasColumnName("new_assignee_id"); b.Property(x=>x.Notes).HasColumnName("notes").HasMaxLength(1000); b.HasOne(x=>x.FarmTask).WithMany(x=>x.History).HasForeignKey(x=>x.FarmTaskId).OnDelete(DeleteBehavior.Cascade); b.HasOne<AppUser>().WithMany().HasForeignKey(x=>x.ActorUserId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x=>new{x.FarmTaskId,x.CreatedAtUtc}); }
}
