using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SmartFarm.Domain.Entities;

namespace SmartFarm.Infrastructure.Persistence.Configurations;

internal sealed class TelemetryReadingConfiguration : IEntityTypeConfiguration<TelemetryReading>
{
    public void Configure(EntityTypeBuilder<TelemetryReading> b)
    {
        b.ToTable("telemetry_readings"); b.HasKey(x => x.Id); DeploymentRequestConfiguration.IdAudit(b); b.Property(x => x.TenantId).HasColumnName("tenant_id"); b.Property(x => x.FarmId).HasColumnName("farm_id"); b.Property(x => x.ZoneId).HasColumnName("zone_id"); b.Property(x => x.DeviceId).HasColumnName("device_id"); b.Property(x => x.GatewayId).HasColumnName("gateway_id"); b.Property(x => x.MessageId).HasColumnName("message_id").HasMaxLength(100); b.Property(x => x.ParameterCode).HasColumnName("parameter_code").HasConversion<string>().HasMaxLength(30); b.Property(x => x.Value).HasColumnName("value").HasPrecision(18, 4); b.Property(x => x.Unit).HasColumnName("unit").HasMaxLength(30); b.Property(x => x.CapturedAtUtc).HasColumnName("captured_at_utc"); b.Property(x => x.ReceivedAtUtc).HasColumnName("received_at_utc"); b.HasIndex(x => new { x.DeviceId, x.MessageId, x.ParameterCode }).IsUnique(); b.HasIndex(x => new { x.DeviceId, x.CapturedAtUtc, x.ParameterCode }).IsUnique(); b.HasIndex(x => new { x.ZoneId, x.ParameterCode, x.CapturedAtUtc }); b.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Farm>().WithMany().HasForeignKey(x => x.FarmId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Zone).WithMany().HasForeignKey(x => x.ZoneId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Device).WithMany().HasForeignKey(x => x.DeviceId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Gateway).WithMany().HasForeignKey(x => x.GatewayId).OnDelete(DeleteBehavior.Restrict);
    }
}

internal sealed class AlertRuleConfiguration : IEntityTypeConfiguration<AlertRule>
{
    public void Configure(EntityTypeBuilder<AlertRule> b)
    {
        b.ToTable("alert_rules", t => { t.HasCheckConstraint("ck_alert_rules_range", "min_threshold <= max_threshold"); t.HasCheckConstraint("ck_alert_rules_cooldown", "cooldown_minutes BETWEEN 1 AND 1440"); }); b.HasKey(x => x.Id); DeploymentRequestConfiguration.IdAudit(b); b.Property(x => x.ZoneId).HasColumnName("zone_id"); b.Property(x => x.GrowthStageId).HasColumnName("growth_stage_id"); b.Property(x => x.ParameterCode).HasColumnName("parameter_code").HasConversion<string>().HasMaxLength(30); b.Property(x => x.MinThreshold).HasColumnName("min_threshold").HasPrecision(18, 4); b.Property(x => x.MaxThreshold).HasColumnName("max_threshold").HasPrecision(18, 4); b.Property(x => x.Severity).HasColumnName("severity").HasConversion<string>().HasMaxLength(20); b.Property(x => x.CooldownMinutes).HasColumnName("cooldown_minutes"); b.Property(x => x.IsActive).HasColumnName("is_active"); b.Property(x => x.IsSystemGenerated).HasColumnName("is_system_generated"); b.Property(x => x.ArchivedAtUtc).HasColumnName("archived_at_utc"); b.HasIndex(x => new { x.ZoneId, x.GrowthStageId, x.ParameterCode, x.Severity }).IsUnique().HasFilter("archived_at_utc IS NULL"); b.HasOne(x => x.Zone).WithMany().HasForeignKey(x => x.ZoneId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.GrowthStage).WithMany().HasForeignKey(x => x.GrowthStageId).OnDelete(DeleteBehavior.Restrict);
    }
}

internal sealed class AlertRuleEvaluationStateConfiguration : IEntityTypeConfiguration<AlertRuleEvaluationState>
{
    public void Configure(EntityTypeBuilder<AlertRuleEvaluationState> b) { b.ToTable("alert_rule_evaluation_states"); b.HasKey(x => new { x.AlertRuleId, x.DeviceId }); b.Property(x => x.AlertRuleId).HasColumnName("alert_rule_id"); b.Property(x => x.DeviceId).HasColumnName("device_id"); b.Property(x => x.ConsecutiveViolationCount).HasColumnName("consecutive_violation_count"); b.Property(x => x.LastViolationAtUtc).HasColumnName("last_violation_at_utc"); b.Property(x => x.LastAlertAtUtc).HasColumnName("last_alert_at_utc"); b.Property(x => x.LastMessageId).HasColumnName("last_message_id").HasMaxLength(100); b.HasOne(x => x.AlertRule).WithMany(x => x.EvaluationStates).HasForeignKey(x => x.AlertRuleId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Device).WithMany().HasForeignKey(x => x.DeviceId).OnDelete(DeleteBehavior.Restrict); }
}

internal sealed class AlertConfiguration : IEntityTypeConfiguration<Alert>
{
    public void Configure(EntityTypeBuilder<Alert> b) { b.ToTable("alerts"); b.HasKey(x => x.Id); DeploymentRequestConfiguration.IdAudit(b); b.Property(x => x.TenantId).HasColumnName("tenant_id"); b.Property(x => x.FarmId).HasColumnName("farm_id"); b.Property(x => x.ZoneId).HasColumnName("zone_id"); b.Property(x => x.DeviceId).HasColumnName("device_id"); b.Property(x => x.AlertRuleId).HasColumnName("alert_rule_id"); b.Property(x => x.PlantingSeasonId).HasColumnName("planting_season_id"); b.Property(x => x.GrowthStageId).HasColumnName("growth_stage_id"); b.Property(x => x.ParameterCode).HasColumnName("parameter_code").HasConversion<string>().HasMaxLength(30); b.Property(x => x.ObservedValue).HasColumnName("observed_value").HasPrecision(18, 4); b.Property(x => x.MinThreshold).HasColumnName("min_threshold").HasPrecision(18, 4); b.Property(x => x.MaxThreshold).HasColumnName("max_threshold").HasPrecision(18, 4); b.Property(x => x.Unit).HasColumnName("unit").HasMaxLength(30); b.Property(x => x.Severity).HasColumnName("severity").HasConversion<string>().HasMaxLength(20); b.Property(x => x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(20); b.Property(x => x.Title).HasColumnName("title").HasMaxLength(300); b.Property(x => x.AcknowledgedAtUtc).HasColumnName("acknowledged_at_utc"); b.Property(x => x.ResolvedAtUtc).HasColumnName("resolved_at_utc"); b.HasIndex(x => new { x.ZoneId, x.ParameterCode, x.Severity, x.Status }); b.HasOne<Tenant>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Farm>().WithMany().HasForeignKey(x => x.FarmId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PlantingSeason>().WithMany().HasForeignKey(x => x.PlantingSeasonId).OnDelete(DeleteBehavior.Restrict); b.HasOne<GrowthStage>().WithMany().HasForeignKey(x => x.GrowthStageId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Zone).WithMany().HasForeignKey(x => x.ZoneId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Device).WithMany().HasForeignKey(x => x.DeviceId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.AlertRule).WithMany().HasForeignKey(x => x.AlertRuleId).OnDelete(DeleteBehavior.Restrict); }
}

internal sealed class AlertHistoryEventConfiguration : IEntityTypeConfiguration<AlertHistoryEvent>
{
    public void Configure(EntityTypeBuilder<AlertHistoryEvent> b) { b.ToTable("alert_history_events"); b.HasKey(x => x.Id); DeploymentRequestConfiguration.IdAudit(b); b.Property(x => x.AlertId).HasColumnName("alert_id"); b.Property(x => x.ActorUserId).HasColumnName("actor_user_id"); b.Property(x => x.EventType).HasColumnName("event_type").HasConversion<string>().HasMaxLength(30); b.Property(x => x.ActionTaken).HasColumnName("action_taken").HasMaxLength(2000); b.Property(x => x.Notes).HasColumnName("notes").HasMaxLength(2000); b.HasOne(x => x.Alert).WithMany(x => x.History).HasForeignKey(x => x.AlertId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.ActorUser).WithMany().HasForeignKey(x => x.ActorUserId).OnDelete(DeleteBehavior.Restrict); }
}
